"""
error_recovery.py – Error Recovery & Graceful Degradation (Gold Tier Feature 5)

Provides:
  1. ErrorRecovery context manager — catches exceptions across any pipeline stage,
     writes a structured recovery note to Vault/Needs_Action/, and logs to audit trail.
  2. health_check() — tests connectivity for Gmail, Groq, WhatsApp, and MCP servers.
  3. recover_stale_inbox() — re-queues inbox items older than MAX_INBOX_AGE hours.

Usage:
    from error_recovery import ErrorRecovery, health_check

    with ErrorRecovery("gmail_watcher", "Fetch new emails"):
        gmail_watcher.run_once()

    report = health_check()
    print(report)
"""

import logging
import os
import sys
import traceback
from contextlib import contextmanager
from datetime import datetime, timedelta
from pathlib import Path

BASE_DIR = Path(__file__).parent
VAULT_ROOT = BASE_DIR / "Vault"
LOG_FILE = BASE_DIR / "error_recovery.log"
MAX_INBOX_AGE_HOURS = 24  # re-queue inbox items older than this

import io
_console = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.FileHandler(LOG_FILE, encoding="utf-8"),
        logging.StreamHandler(_console),
    ],
)
log = logging.getLogger("error-recovery")


# ---------------------------------------------------------------------------
# Error Recovery Context Manager
# ---------------------------------------------------------------------------

@contextmanager
def ErrorRecovery(component: str, operation: str, notify_vault: bool = True):
    """
    Context manager that catches exceptions, logs them, and optionally writes
    a recovery note to Vault/Needs_Action/.

    Usage:
        with ErrorRecovery("gmail_watcher", "Fetch emails"):
            do_something()
    """
    try:
        yield
    except KeyboardInterrupt:
        raise  # always propagate Ctrl+C
    except Exception as exc:
        tb = traceback.format_exc()
        log.error("[%s] %s FAILED: %s", component, operation, exc)
        log.debug("Traceback:\n%s", tb)

        if notify_vault:
            _write_error_note(component, operation, exc, tb)

        # Do NOT re-raise — caller continues gracefully


def _write_error_note(component: str, operation: str, exc: Exception, tb: str) -> None:
    """Write a structured error note to Vault/Needs_Action/."""
    try:
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        fname = f"ERROR_{component}_{ts}.md"
        path = VAULT_ROOT / "Needs_Action" / fname
        path.parent.mkdir(parents=True, exist_ok=True)

        # Recovery suggestions based on error type
        suggestion = _recovery_suggestion(component, str(exc))

        content = f"""---
source: error_recovery
received: {datetime.now().strftime("%Y-%m-%d %H:%M")}
status: needs_action
priority: high
tags: [error, {component}]
summary: "{component} error: {str(exc)[:80]}"
---

# Error Report: {component}

**Component:** `{component}`
**Operation:** {operation}
**Time:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Error:** `{exc}`

## Recovery Suggestion

{suggestion}

## Full Traceback

```
{tb.strip()}
```

---
*Auto-generated by error_recovery.py — move to Done/ when resolved.*
"""
        path.write_text(content, encoding="utf-8")
        log.info("[ErrorRecovery] Wrote recovery note: Needs_Action/%s", fname)
    except Exception as write_exc:
        log.error("[ErrorRecovery] Could not write error note: %s", write_exc)


def _recovery_suggestion(component: str, error_msg: str) -> str:
    """Return a human-readable recovery suggestion based on component and error."""
    error_lower = error_msg.lower()

    if "token" in error_lower or "auth" in error_lower or "credential" in error_lower or "oauth" in error_lower:
        return (f"**Auth/Token Issue** — re-run OAuth flow:\n"
                f"```\nuv run python gmail_watcher.py  # re-auth Gmail\n"
                f"uv run python linkedin_poster.py --auth  # re-auth LinkedIn\n```")

    if "rate limit" in error_lower or "429" in error_lower or "quota" in error_lower:
        return ("**Rate Limit** — wait 1-5 minutes and retry. "
                "Consider reducing polling frequency in the relevant watcher.")

    if "connection" in error_lower or "timeout" in error_lower or "network" in error_lower:
        return ("**Network Issue** — check internet connection. "
                f"`{component}` will retry on next scheduled run.")

    if "whatsapp" in component.lower():
        return ("**WhatsApp Issue** — check WhatsApp Web is open in the browser session.\n"
                "Run: `uv run python whatsapp_watcher.py` to restart the watcher.")

    if "gmail" in component.lower():
        return ("**Gmail Issue** — check that `token.json` exists and is valid.\n"
                "Run: `uv run python gmail_watcher.py` to re-authenticate.")

    if "groq" in error_lower or "openrouter" in error_lower:
        return ("**AI Router Issue** — check API keys in `.env`:\n"
                "- `GROQ_API_KEY`\n- `OPENROUTER_API_KEY`")

    return (f"**Unknown error in `{component}`** — review the traceback above and restart the component.\n"
            f"Run: `uv run python {component}.py` to restart manually.")


# ---------------------------------------------------------------------------
# Health Check
# ---------------------------------------------------------------------------

def health_check() -> dict:
    """
    Test connectivity for all pipeline components.
    Returns dict: {component: {"status": "ok"|"error", "detail": str}}
    """
    results = {}

    # Groq
    try:
        from router import _call_groq
        r = _call_groq("Respond with: OK", "ping")
        results["groq"] = {"status": "ok" if r else "error", "detail": r or "No response"}
    except Exception as exc:
        results["groq"] = {"status": "error", "detail": str(exc)}

    # Gmail token
    token_path = BASE_DIR / "token.json"
    results["gmail_token"] = {
        "status": "ok" if token_path.exists() else "error",
        "detail": "token.json exists" if token_path.exists() else "token.json missing — run gmail_watcher.py to authenticate",
    }

    # Calendar token
    cal_token = BASE_DIR / "calendar_token.json"
    results["calendar_token"] = {
        "status": "ok" if cal_token.exists() else "warning",
        "detail": "Token exists" if cal_token.exists() else "calendar_token.json missing — run calendar_mcp_server.py once",
    }

    # WhatsApp session dir
    wa_session = BASE_DIR / "whatsapp_session"
    results["whatsapp_session"] = {
        "status": "ok" if wa_session.exists() else "warning",
        "detail": "Session dir exists" if wa_session.exists() else "No WhatsApp session — run whatsapp_watcher.py to create",
    }

    # Vault folders
    for folder in ["Inbox", "Needs_Action", "Done", "Approved", "Pending_Approval"]:
        p = VAULT_ROOT / folder
        results[f"vault_{folder.lower()}"] = {
            "status": "ok" if p.exists() else "error",
            "detail": f"{p} exists" if p.exists() else f"Missing folder: {p}",
        }

    return results


def print_health_report(results: dict) -> None:
    """Print a formatted health check report."""
    print(f"\n{'='*50}")
    print(f"  AI Employee Health Check — {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    print(f"{'='*50}")
    ok = sum(1 for v in results.values() if v["status"] == "ok")
    total = len(results)
    for component, info in results.items():
        icon = {"ok": "✅", "error": "❌", "warning": "⚠️"}.get(info["status"], "?")
        print(f"  {icon} {component:<25} {info['detail']}")
    print(f"{'='*50}")
    print(f"  {ok}/{total} components healthy")
    print(f"{'='*50}\n")


# ---------------------------------------------------------------------------
# Stale Inbox Recovery
# ---------------------------------------------------------------------------

def recover_stale_inbox() -> int:
    """
    Re-triage inbox items that have been sitting for more than MAX_INBOX_AGE_HOURS.
    Moves stale items to Needs_Action/ with a note.
    Returns count of items recovered.
    """
    inbox = VAULT_ROOT / "Inbox"
    if not inbox.exists():
        return 0

    cutoff = datetime.now() - timedelta(hours=MAX_INBOX_AGE_HOURS)
    count = 0
    for f in inbox.glob("*.md"):
        mtime = datetime.fromtimestamp(f.stat().st_mtime)
        if mtime < cutoff:
            log.warning("[StaleInbox] %s has been in Inbox for >%dh — escalating",
                        f.name, MAX_INBOX_AGE_HOURS)
            try:
                from vault_io import VaultIO
                vault = VaultIO()
                # Stamp frontmatter and move
                content = f.read_text(encoding="utf-8")
                if not content.startswith("---"):
                    content = f"""---
source: inbox_recovery
received: {mtime.strftime("%Y-%m-%d %H:%M")}
status: needs_action
priority: medium
tags: [stale, inbox_recovery]
summary: "Stale inbox item — was not triaged within {MAX_INBOX_AGE_HOURS}h"
---

{content}"""
                dest = vault.needs_action / f.name
                dest.write_text(content, encoding="utf-8")
                f.unlink()
                log.info("[StaleInbox] Moved %s → Needs_Action/", f.name)
                count += 1
            except Exception as exc:
                log.error("[StaleInbox] Failed to move %s: %s", f.name, exc)
    return count


# ---------------------------------------------------------------------------
# Main (CLI health check)
# ---------------------------------------------------------------------------

def main():
    import argparse
    parser = argparse.ArgumentParser(description="AI Employee Error Recovery & Health Check")
    parser.add_argument("--health", action="store_true", help="Run health check")
    parser.add_argument("--recover-inbox", action="store_true", help="Recover stale inbox items")
    args = parser.parse_args()

    if args.health:
        results = health_check()
        print_health_report(results)

    if args.recover_inbox:
        n = recover_stale_inbox()
        print(f"Recovered {n} stale inbox item(s).")

    if not any([args.health, args.recover_inbox]):
        parser.print_help()


if __name__ == "__main__":
    main()
